### ISSUE TITLE
loop2bigInteract.sh script does not seem to work

### ISSUE THREAD

**Issue by marcora** [zhaoshuoxp/Converters#1]
It looks like this script may be written for an old version of the HiCCUPS loops format. I am using merged_loops.bedpe from Juicer and it does not convert to valid 5+13.bed (sortBed complains and does not proceed).

the header row in bedpe does not start with # and perhaps other columns have changed position.

**Comment by zhaoshuoxp** [comment]
> It looks like this script may be written for an old version of the HiCCUPS loops format. I am using merged_loops.bedpe from Juicer and it does not convert to valid 5+13.bed (sortBed complains and does not proceed).
> 
> the header row in bedpe does not start with # and perhaps other columns have changed position.

Hi Marcora, I just tried the most updated juciertools v1.22.01 and it works fine on my end. 
The output of HiCCUPS looks like:
#chr1	x1	x2	chr2	y1	y2	name	score	strand1	strand2	color	observed	expectedBL	expectedDonut	expectedH	expectedV	fdrBL	fdrDonut	fdrH	fdrV	numCollapsed	centroid1	centroid2	radius
# juicer_tools version 1.22.01
10	4990000	5000000	10	5050000	5060000	.	.	.	.	0,255,255	21.0	0.92182726	0.9502513	0.9755429	0.9763188	3.8777423E-12	3.4910796E-12	3.3227021E-12	3.4888065E-12	1	4995000	5055000	0
10	5475000	5500000	10	5650000	5675000	.	.	.	.	0,255,255	22.0	3.504882	3.336007	4.0206256	3.2574532	3.2848545E-6	1.4051591E-6	5.6575107E-5	2.4292076E-6	1	54875005662500	0
10	35400000	35425000	10	35500000	35525000	.	.	.	.	0,255,255	27.0	6.9692454	6.174317	6.8534102	6.1850934	1.0118395E-4	2.1230396E-6	1.2760221E-4	3.2253517E-6	1	35412500	35512500	0
10	59925000	59950000	10	60050000	60075000	.	.	.	.	0,255,255	33.0	9.87222	9.147767	12.345406	7.1425357	0.001218689	1.1776135E-5	0.0011105601	1.2506905E-7	1	59937500	60062500	0
10	55750000	55775000	10	56150000	56175000	.	.	.	.	0,255,255	38.0	9.279071	7.901377	8.212449	9.436843	2.901498E-8	3.5041275E-8	4.912812E-8	5.368894E-8	1	55762500	56162500	0
10	54050000	54075000	10	54225000	54250000	.	.	.	.	0,255,255	35.0	8.305509	7.7888904	9.96624	8.942315	1.0580204E-6	5.2843205E-9	1.9784596E-4	1.4302842E-6	2	54062500	54250000	12500
10	118975000	119000000	10	119075000	119100000	.	.	.	.	0,255,255	34.0	6.8376856	5.758898	7.298901	5.3348093	3.9179657E-8	1.4505905E-10	4.2490402E-8	1.9092167E-10	1	118987500	119087500	0
10	63775000	63800000	10	64000000	64025000	.	.	.	.	0,255,255	32.0	6.4370966	5.578972	4.734364	6.294963	3.6541397E-7	2.3979585E-9	3.3028535E-11	3.9665989E-7	2	63800000	64000000	17678

We are using HICCPUS CPU algorithm because we don't have CUDA cores on our server, but it should generate the same output format according to the author's documentation. Is that possible for you to post the head lines to see what's going on there?
